FROM node:22-alpine as npm-builder

WORKDIR /app
COPY ./frontend .
RUN npm install
RUN npm run build
RUN ls -l
RUN ls -l ./dist

FROM golang:1.22-alpine

WORKDIR /app

RUN mkdir /frontend
COPY --from=npm-builder /app/dist /app/frontend/dist

COPY go.mod ./
RUN go mod tidy

# Install envsubst
RUN apk add --no-cache gettext

COPY . .
RUN go build -o main .

RUN chmod +x entrypoint.sh

CMD ["./entrypoint.sh"]